### PR TITLE
Fixes Missing/invalid DB name error

### LINKED ISSUE #38: db_name not defined
if I do not use proxy then I see error db_name not defined.
With v1.3.5 it work fine.

Why there done() and then() after it?
https://github.com/nolanlawson/pouchdb-load/blob/2edb5f6652fc171cc7935fbfd6324e913cca2835/lib/index.js#L49

https://github.com/nolanlawson/pouchdb-load/blob/2edb5f6652fc171cc7935fbfd6324e913cca2835/lib/index.js#L56
info is undefined if no proxy

### PR DESCRIPTION
**Pull request by jkleinsc**
This PR fixes #38 in which the error is being thrown: Missing/invalid DB name

Because of where this error is thrown, I don't think there is a way to catch this in the tests, so I did not modify the tests.

### CODE REVIEW

File: lib/index.js [hunk 1]
```diff
@@ -51,6 +51,9 @@ function loadString(db, data, opts, callback) {
 
     return db.info();
```
Comment (nolanlawson) [inline lib/index.js]: another fix is to just join the next `then()` to the previous `db.info()` which I think is cleaner

**Comment by nolanlawson** [comment]
merged, see #48
